remote_theme: pmarsceill/just-the-docs

title: Steph's µLab
description: This tutorial presents a comparative analysis of the advanced sleep modes of ESP32. You are guided step by step through different experiments by programming the microcontroller with C++.

baseurl: "/sleep-modes"
permalink: pretty
timezone: Indian/Reunion
search_enabled: false
heading_anchors: true

exclude: [README.md, LICENSE]

aux_links:
  "Random Nerd Tutorials":
    - "https://randomnerdtutorials.com"
  "RNT Lab Forum":
    - "https://rntlab.com/forum/"

#footer_content: "Copyright &copy; 2020 Stéphane Calderoni"

# Google Analytics Tracking
ga_tracking: UA-1998450-3